apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-data
  namespace: wiki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: azuredisk-premium-retain
