replicaCount: 1

ingress:
  enabled: false

service:
  type: ClusterIP

persistence:
  enabled: true
  existingClaim: nextcloud-data
  accessMode: ReadWriteOnce
  size: 200Gi

nextcloud:
  host: "${cloud_domain}"
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
    usernameKey: NEXTCLOUD_USER
    passwordKey: NEXTCLOUD_PW

internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
    hostKey: DB_HOST
    databaseKey: DB_NAME
    usernameKey: DB_USER
    passwordKey: DB_PASSWORD

redis:
  enabled: false

externalRedis:
  enabled: true
  host: ${redis_host}
  port: ${redis_port}

resources:
  requests:
    cpu: "1"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"
