apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nextcloud-azuredisk
  resources:
    requests:
      storage: 64Gi
