kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azuredisk-standard-retain
provisioner: disk.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
