apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: redis
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azuredisk-premium-retain
  resources:
    requests:
      storage: 4Gi
